version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: logitrack-postgres
    environment:
      POSTGRES_USER: logitrack
      POSTGRES_PASSWORD: logitrack_pass
      POSTGRES_DB: logitrack_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: logitrack-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
