"use client";

import React from "react";
import { useLanguageStore } from "../../../../store/languageStore";

export default function TaskDashboardPage() {
  const { t } = useLanguageStore();

  return (
    <div className="p-6 bg-[#f4f7fb] min-h-full">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-800">{t("taskDashboard")}</h1>
        <p className="text-sm text-gray-500 mt-1">{t("dashboardSubtitle")}</p>
      </div>

      {/* Top Row KPIs */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-6">
        <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex items-center justify-between">
          <div>
            <p className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">{t("totalOpenTasks")}</p>
            <h3 className="text-3xl font-bold text-gray-800">42</h3>
          </div>
          <div className="w-12 h-12 rounded-full bg-blue-50 flex items-center justify-center text-blue-500">
            <span className="material-symbols-outlined text-[24px]">assignment</span>
          </div>
        </div>
        <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex items-center justify-between">
          <div>
            <p className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">{t("overdueTasks")}</p>
            <h3 className="text-3xl font-bold text-red-600">8</h3>
          </div>
          <div className="w-12 h-12 rounded-full bg-red-50 flex items-center justify-center text-red-500">
            <span className="material-symbols-outlined text-[24px]">warning</span>
          </div>
        </div>
        <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex items-center justify-between">
          <div>
            <p className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">{t("blockedTasks")}</p>
            <h3 className="text-3xl font-bold text-orange-600">3</h3>
          </div>
          <div className="w-12 h-12 rounded-full bg-orange-50 flex items-center justify-center text-orange-500">
            <span className="material-symbols-outlined text-[24px]">block</span>
          </div>
        </div>
        <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex items-center justify-between">
          <div>
            <p className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">{t("autoGeneratedThisWeek")}</p>
            <h3 className="text-3xl font-bold text-gray-800">156</h3>
          </div>
          <div className="w-12 h-12 rounded-full bg-purple-50 flex items-center justify-center text-purple-500">
            <span className="material-symbols-outlined text-[24px]">smart_toy</span>
          </div>
        </div>
      </div>

      {/* Middle Row Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
        {/* Tasks by Status */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
          <h3 className="font-semibold text-gray-800 mb-6">{t("tasksByStatus")}</h3>
          <div className="flex items-center justify-center gap-12">
            {/* Mock Doughnut Chart (CSS based) */}
            <div className="relative w-48 h-48 rounded-full flex items-center justify-center" 
                 style={{ background: 'conic-gradient(#00b894 0% 45%, #0984e3 45% 75%, #e17055 75% 90%, #fdcb6e 90% 100%)' }}>
              <div className="w-32 h-32 bg-white rounded-full flex flex-col items-center justify-center shadow-inner">
                <span className="text-3xl font-bold text-gray-800">142</span>
                <span className="text-xs text-gray-500">Total This Month</span>
              </div>
            </div>
            
            <div className="space-y-4">
              <div className="flex items-center gap-3">
                <div className="w-3 h-3 rounded-full bg-[#00b894]"></div>
                <div className="flex flex-col">
                  <span className="text-sm font-medium text-gray-700">Hecho (45%)</span>
                  <span className="text-xs text-gray-500">64 tasks</span>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-3 h-3 rounded-full bg-[#0984e3]"></div>
                <div className="flex flex-col">
                  <span className="text-sm font-medium text-gray-700">En Curso (30%)</span>
                  <span className="text-xs text-gray-500">42 tasks</span>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-3 h-3 rounded-full bg-[#e17055]"></div>
                <div className="flex flex-col">
                  <span className="text-sm font-medium text-gray-700">Bloqueada (15%)</span>
                  <span className="text-xs text-gray-500">21 tasks</span>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-3 h-3 rounded-full bg-[#fdcb6e]"></div>
                <div className="flex flex-col">
                  <span className="text-sm font-medium text-gray-700">Pendiente (10%)</span>
                  <span className="text-xs text-gray-500">15 tasks</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Task Volume over time */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex flex-col">
          <div className="flex justify-between items-center mb-6">
            <h3 className="font-semibold text-gray-800">{t("taskVolumeOverTime")}</h3>
            <select className="text-xs border-gray-300 rounded text-gray-600 bg-gray-50 p-1">
              <option>Last 7 Days</option>
              <option>This Month</option>
            </select>
          </div>
          
          <div className="flex-1 flex items-end justify-between gap-2 px-2 pt-4 border-b border-gray-200 pb-2 relative h-48">
             {/* Y-axis labels */}
             <div className="absolute left-0 top-0 h-full flex flex-col justify-between text-[10px] text-gray-400 pb-2">
               <span>50</span>
               <span>25</span>
               <span>0</span>
             </div>
             <div className="absolute left-6 right-0 top-1 border-t border-dashed border-gray-100"></div>
             <div className="absolute left-6 right-0 top-1/2 border-t border-dashed border-gray-100"></div>
             
             {/* Bars */}
             <div className="ml-8 w-1/7 flex flex-col items-center gap-2 group">
               <div className="w-8 bg-blue-100 rounded-t flex flex-col justify-end group-hover:bg-blue-200 transition-colors" style={{ height: '60%' }}>
                 <div className="w-full bg-[#0984e3] rounded-t" style={{ height: '40%' }}></div>
               </div>
               <span className="text-[10px] text-gray-500">Mon</span>
             </div>
             <div className="w-1/7 flex flex-col items-center gap-2 group">
               <div className="w-8 bg-blue-100 rounded-t flex flex-col justify-end group-hover:bg-blue-200 transition-colors" style={{ height: '80%' }}>
                 <div className="w-full bg-[#0984e3] rounded-t" style={{ height: '60%' }}></div>
               </div>
               <span className="text-[10px] text-gray-500">Tue</span>
             </div>
             <div className="w-1/7 flex flex-col items-center gap-2 group">
               <div className="w-8 bg-blue-100 rounded-t flex flex-col justify-end group-hover:bg-blue-200 transition-colors" style={{ height: '40%' }}>
                 <div className="w-full bg-[#0984e3] rounded-t" style={{ height: '80%' }}></div>
               </div>
               <span className="text-[10px] text-gray-500">Wed</span>
             </div>
             <div className="w-1/7 flex flex-col items-center gap-2 group">
               <div className="w-8 bg-blue-100 rounded-t flex flex-col justify-end group-hover:bg-blue-200 transition-colors" style={{ height: '90%' }}>
                 <div className="w-full bg-[#0984e3] rounded-t" style={{ height: '50%' }}></div>
               </div>
               <span className="text-[10px] text-gray-500 font-bold text-gray-800">Thu</span>
             </div>
             <div className="w-1/7 flex flex-col items-center gap-2 group">
               <div className="w-8 bg-blue-100 rounded-t flex flex-col justify-end group-hover:bg-blue-200 transition-colors" style={{ height: '70%' }}>
                 <div className="w-full bg-[#0984e3] rounded-t" style={{ height: '30%' }}></div>
               </div>
               <span className="text-[10px] text-gray-500">Fri</span>
             </div>
             <div className="w-1/7 flex flex-col items-center gap-2 group">
               <div className="w-8 bg-blue-100 rounded-t flex flex-col justify-end group-hover:bg-blue-200 transition-colors" style={{ height: '30%' }}>
                 <div className="w-full bg-[#0984e3] rounded-t" style={{ height: '90%' }}></div>
               </div>
               <span className="text-[10px] text-gray-500">Sat</span>
             </div>
             <div className="w-1/7 flex flex-col items-center gap-2 group">
               <div className="w-8 bg-blue-100 rounded-t flex flex-col justify-end group-hover:bg-blue-200 transition-colors" style={{ height: '20%' }}>
                 <div className="w-full bg-[#0984e3] rounded-t" style={{ height: '50%' }}></div>
               </div>
               <span className="text-[10px] text-gray-500">Sun</span>
             </div>
          </div>
          <div className="flex justify-center gap-6 mt-4">
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded bg-blue-100"></div>
              <span className="text-xs text-gray-500">Created</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded bg-[#0984e3]"></div>
              <span className="text-xs text-gray-500">Completed</span>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Row Lists */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Most Active Users */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
          <h3 className="font-semibold text-gray-800 mb-4">{t("mostActiveUsers")}</h3>
          <div className="space-y-4">
            {[
              { name: "M. Rodriguez", role: "Warehouse Manager", completed: 124, avgTime: "1.2h", color: "#1466c0", initials: "MR" },
              { name: "J. Smith", role: "Forklift Operator", completed: 98, avgTime: "45m", color: "#00b894", initials: "JS" },
              { name: "L. Chen", role: "Inventory Specialist", completed: 86, avgTime: "2.1h", color: "#e17055", initials: "LC" },
              { name: "A. Patel", role: "Picker", completed: 72, avgTime: "30m", color: "#6c5ce7", initials: "AP" }
            ].map((user, idx) => (
              <div key={idx} className="flex items-center justify-between p-3 rounded-lg border border-gray-100 hover:bg-gray-50 transition-colors">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full flex items-center justify-center text-white font-bold text-sm shadow-sm" style={{ backgroundColor: user.color }}>
                    {user.initials}
                  </div>
                  <div>
                    <h4 className="font-semibold text-gray-800 text-sm">{user.name}</h4>
                    <p className="text-[11px] text-gray-500">{user.role}</p>
                  </div>
                </div>
                <div className="text-right">
                  <p className="text-sm font-bold text-[#00b894]">{user.completed} <span className="text-xs font-normal text-gray-500">tasks</span></p>
                  <p className="text-[11px] text-gray-400">Avg time: {user.avgTime}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Tasks by Type */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
          <h3 className="font-semibold text-gray-800 mb-4">{t("tasksByType")}</h3>
          <div className="space-y-5">
            {[
              { type: "Receiving", count: 85, total: 100, color: "bg-blue-500" },
              { type: "Picking / Packing", count: 120, total: 150, color: "bg-[#00b894]" },
              { type: "Inventory Audits", count: 32, total: 40, color: "bg-orange-500" },
              { type: "Returns Processing", count: 18, total: 30, color: "bg-purple-500" },
              { type: "Incidents / Maintenance", count: 5, total: 10, color: "bg-red-500" },
            ].map((item, idx) => (
              <div key={idx}>
                <div className="flex justify-between text-sm mb-1">
                  <span className="font-medium text-gray-700">{item.type}</span>
                  <span className="text-gray-500 text-xs">{item.count} / {item.total}</span>
                </div>
                <div className="w-full bg-gray-100 rounded-full h-2">
                  <div className={`${item.color} h-2 rounded-full`} style={{ width: `${(item.count / item.total) * 100}%` }}></div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

    </div>
  );
}
